# Generated by Django 2.2.6 on 2020-06-07 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Вид животного')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('description', models.TextField(help_text='Описание данного животного', verbose_name='Описание')),
                ('receipt_date', models.DateField(default=datetime.date(2020, 6, 7), verbose_name='Дата поступления')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('animal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animals_shelter.AnimalType', verbose_name='Тип животного')),
            ],
        ),
    ]
